### ISSUE TITLE
fabric8-maven-plugin:3.1.92:resource fails for no Docker image

### ISSUE THREAD

**Issue by RadekKoubsky** [snowdrop/rest_springboot-tomcat#35]
Running `mvn clean fabric8:deploy -Popenshift -DskipTests` results into the following error:

```[ERROR] Failed to execute goal io.fabric8:fabric8-maven-plugin:3.1.92:resource (default) on project springboot-rest: Execution default of goal io.fabric8:fabric8-maven-plugin:3.1.92:resource failed: Container springboot-rest has no Docker image configured. Please check your Docker image configuration (including the generators which are supposed to run) -> [Help 1]```

Changing the FMP version to 3.3.0 solves the problem, but another one with the java image shows up (the running container cannot execute the jar):

`Starting the Java application using /opt/run-java/run-java.sh ...
ERROR: Neither $JAVA_MAIN_CLASS nor $JAVA_APP_JAR is set and 31 found in /deployments (1 expected)`

Note:
[vertx-http-booster](https://github.com/openshiftio-vertx-boosters/vertx-http-booster) uses different version of FMP plugin: [3.2.28](https://github.com/openshiftio-vertx-boosters/vertx-http-booster/blob/master/pom.xml#L41)

I expect that he FMP version will be unified in BOM or parent for all boosters.

**Comment by gytis** [comment]
booster-parent was released yesterday (https://github.com/openshiftio/booster-parent/blob/booster-parent-1/pom.xml). I'm updating the quickstart to use it.

**Comment by gytis** [comment]
Fixed: https://github.com/snowdrop/rest_springboot-tomcat/commit/6799df0687f49c0f3c7b0855caf00c3ea3d7d69d
